spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/eazybankdev/protocol/openid-connect/certs